# Menus
menu:
  首页: .
  归档: archives
  主站: http://www.xujin.org
  社区: http://springcloud.cn
  关于我: about



# Customize
customize:
    logo:
        enabled: true
        width: 55
        height: 55
        url: images/logo.png
    profile:
        enabled: true # Whether to show profile bar
        avatar: css/images/avatar.png
        gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
        author: Software_King
        author_title: 软件世界就是模拟客观世界，从而需求分析，技术驱动，改造世界！
        location: ShangHai, China
        follow: about
    highlight: tomorrow
    sidebar: right # sidebar position, options: left, right
    thumbnail: true # enable posts thumbnail, options: true, false
    favicon: /css/images/favicon.ico
    social_links:
        github: http://github.com/softwareking
        git: http://git.oschina.net/softwareking
        linkedin: http://www.linkedin.com/in/xujins
        weibo: http://weibo.com/softwaremi
        rss: atom.xml
        sitemap: sitemap.xml
    social_link_tooltip: true # enable the social link tooltip, options: true, false

# Widgets
widgets:
    - recent_posts
    - category
    - archive
    - tag
    - tagcloud
    - links

    

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: true # you need to disable other search engines to use Baidu search, options: true, false

# Comment
comment:
    #disqus: hexo-theme-icarus # enter disqus shortname here
    #使用多说评论
    duoshuo: xujin-hexo-blog
    #youyan: # enter youyan uid here

# Share
share: bdshare # options: jiathis, bdshare, addtoany, default
duoshuo_share: true

# Plugins
plugins:
    lightgallery: true # options: true, false
    justified-gallery: true # options: true, false
    google_analytics: # enter the tracking ID for your Google Analytics
    google_site_verification: # enter Google site verification code
    baidu_analytics: # enter Baidu Analytics hash key
    
# highlight.js
#highlight_theme: zenburn

# Miscellaneous
miscellaneous:
   open_graph:
      fb_app_id:
      fb_admins:
      twitter_id:
      google_plus:
   links:
    许进|沉思录: http://www.xujin.org
    Spring Cloud中国社区: http://springcloud.cn
    我的博客园: http://www.cnblogs.com/ACMer/
    新浪博客: http://blog.sina.com.cn/softwaremi
        
